### ISSUE TITLE
Menu text doesn't line up

### ISSUE THREAD

**Issue by tobbenb** [linuxserver/linuxserver.io#8]
The icons of github and donate are on top of the text instead of in front when browsing linuxserver.io on a tablet on chrome 65.0.3325.109 on Android 7. This makes the text to not line up.

![menu](https://user-images.githubusercontent.com/10107585/38194368-6805bd24-3677-11e8-8fce-98a22d5ece37.png)

**Comment by CHBMB** [comment]
This is fixed now so could be closed.

**Comment by tobbenb** [comment]
Still the same here

**Comment by CHBMB** [comment]
My bad, sorry @tobbenb missed the tablet part.....

**Comment by JoshStark** [comment]
Solved in redesign.
